[package]
name = "stump"
version = "0.0.1"
edition = "2021"
default-run = "stump"

[dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.5.0" }
serde = { version = "1.0", features = ["derive"] }
rocket =  { version = "0.5.0-rc.2", features =  ["json" ] }
# rocket-session-store = "0.2.0"
# rocket-session-store = { path = "../../../../../Documents/sandbox/clones/rocket-session-store", features = ["okapi"] }
rocket-session-store = { git = "https://github.com/aaronleopold/rocket-session-store", branch = "develop", features = ["okapi"] }
rocket_cors = "0.6.0-alpha1"
bcrypt = "0.10.1"
anyhow = "1.0.57"
xml-rs = "0.8.4"
serde-xml-rs = "0.5.1"
urlencoding = "2.1.0"
thiserror = "1.0.30"
base64 = "0.13.0"
log = "0.4.0"
epub = "1.2.3"
walkdir = "2.3.2"
zip = "0.5.13"
# unrar = "0.4.4"
unrar = { git = "https://github.com/aaronleopold/unrar.rs", branch = "aleopold--read-bytes" }
async-trait = "0.1.53"
infer = "0.7.0"
dirs = "4.0.0"

ring = "0.16.20"
data-encoding = "2.3.2"
cuid = "1.2.0"
webp = "0.2.2"
image = "0.24.2"
include_dir = "0.7.2"
rocket_okapi = { version = "0.8.0-rc.2", features = ["rapidoc", "swagger"] }
schemars = "0.8.10"
fern = "0.6.1"
toml = "0.5.9"


[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }
# rusqlite = { version = "0.25.4", features = ["bundled"] }
